FROM openjdk:17-jdk

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
COPY wait-for-it.sh . 

# Echo the server.port setting into the application.properties file
# RUN echo "server.port=55551" >> src/main/resources/application.properties

RUN microdnf install -y nc findutils

RUN ./gradlew build

EXPOSE 55551

ENTRYPOINT ["/app/wait-for-it.sh", "nat-dev-db:5433", "--", "java", "-jar","build/libs/server-0.0.1-SNAPSHOT.jar"]
