FROM openjdk:17-jdk

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
COPY wait-for-it.sh . 

RUN microdnf install -y nc findutils
RUN ./gradlew build

EXPOSE 55550

ENTRYPOINT ["/app/wait-for-it.sh", "nat-prod-db:5432", "--", "java", "-jar","build/libs/server-0.0.1-SNAPSHOT.jar"]
