version: '3.9'

services:
  nat-prod-infra:
    container_name: nat-prod-infra
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .default.conf:/etc/nginx/conf.d/default.conf
      - ../client/build:/usr/share/nginx/release
    depends_on:
      - nat-prod-server
  
  nat-prod-server:
    container_name: nat-prod-server
    build:
      context: ../server
      dockerfile: Dockerfile.prod
    ports:
      - "55550:55550"
    
  nat-prod-db:
    container_name: nat-prod-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nat
      MYSQL_USER: s3-prod
      MYSQL_PASSWORD: secret
    volumes:
      - ../db/prod:/var/lib/mysql
      - ../db/sql/init.prod.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
