version: '3.9'

services:
  nat-dev-server:
    container_name: nat-dev-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "55551:55551"
    
  nat-dev-client:
    container_name: nat-dev-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3331:3331'
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["yarn", "start"]
