FROM node:16

WORKDIR /app

COPY package*.json yarn.lock ./
COPY . .

RUN yarn install

ENV NODE_ENV=development
ENV REACT_APP_HOST=http://localhost:55551/api/v1/
ENV PORT=3331

EXPOSE 3331

CMD [ "yarn", "start" ]