FROM node:16

WORKDIR /app

COPY package*.json yarn.lock ./
COPY . .

RUN yarn install

ENV NODE_ENV=development
ENV REACT_APP_HOST=http://10.32.131.34:55551/api/v1/
ENV PORT=4441

EXPOSE 4441

CMD [ "yarn", "start" ]